[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20.18.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Run build daily to refresh events
[build.processing]
  skip_processing = false
